FIX - add required parameter for batchUpdate
It's not possible to use the batchUpdate operation without this param:
```
Fatal error: Uncaught Google\Service\Exception: {
  "error": {
    "code": 400,
    "message": "'valueInputOption' is required but not specified",
    "errors": [
      {
        "message": "'valueInputOption' is required but not specified",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

But adding it will also cause an issue because it's not defined:

```
Google\Exception: (batchUpdate) unknown parameter: 'valueInputOption'
```